

[window]
padding = { x = 10, y = 15}

decorations = "Buttonless"
opacity = 0.65
# blur = true

[mouse]
hide_when_typing = true

[font]

size = 16
normal.family = "JetBrainsMono Nerd Font"

[colors]

primary.background = "#000000"
primary.foreground = "#c7c7c7"

draw_bold_text_with_bright_colors = true

# cursor = {text = "#ffffff", cursor = "#7f7f7f"}

[colors.normal]

black = "#000000"
red = "#c91b00"
green = "#00c200"
yellow = "#c7c400"
blue = "#0225c7"
magenta = "#c930c7"
cyan = "#00c5c7"
white = "#c7c7c7"


[colors.bright]

black = "#676767"
red = "#ff6d67"
green = "#5ff967"
yellow = "#fefb67"
blue = "#6871ff"
magenta = "#ff76ff"
cyan = "#5ffdff"
white = "#fffeff"
